export enum DashboardModuleType {
  PORTFOLIO_OVERVIEW = 'portfolio-overview',
  HOLDINGS = 'holdings',
  PORTFOLIO_SUMMARY = 'portfolio-summary',
  MARKETS = 'markets',
  MARKETS_PREMIUM = 'markets-premium',
  WATCHLIST = 'watchlist',
  PORTFOLIO_ANALYSIS = 'portfolio-analysis',
  ACTIVITIES = 'activities',
  ALLOCATIONS = 'allocations',
  FIRE = 'fire',
  X_RAY = 'x-ray',
  ACCOUNTS = 'accounts',
  ACCOUNT_SETTINGS = 'account-settings',
  ACCOUNT_MEMBERSHIP = 'account-membership',
  ACCOUNT_ACCESS = 'account-access',
  ADMIN_OVERVIEW = 'admin-overview',
  ADMIN_JOBS = 'admin-jobs',
  ADMIN_MARKET_DATA = 'admin-market-data',
  ADMIN_SETTINGS = 'admin-settings',
  ADMIN_USERS = 'admin-users',
  AI_CHAT = 'ai-chat'
}
